# Site settings
title: Swift Tom
author:
  name: Thomas Prezioso
  email: tommyprezioso@gmail.com
description: "Learning the Swift Programming Language"
minima:
  social-network-links:
    twitter: tommyprezioso
    github: Tprezioso

# Build settings
remote_theme: jekyll/minima
