# Site settings
title: Swift Tom
author:
  name: Thomas Prezioso
  email: tommyprezioso@gmail.com
  twitter: @tommyprezioso
description: "Learning the Swift Programming Language"

# Build settings
remote_theme: jekyll/minima
