# Site settings
title: Swift Tom
author:
  name: Thomas Prezioso
  email: tommyprezioso@gmail.com
description: "Learning the Swift Programming Language"

# Build settings
remote_theme: minimal-mistakes-jekyll
minima:
  skin: dark
  social_links:
    twitter: tommyprezioso
    github: Tprezioso
