# Site settings
title: Swift Tom
author: Thomas Prezioso
email: tommyprezioso@gmail.com
description: "Learning the Swift Programming Language"
baseurl: "/swifttom"

# Build settings
remote_theme: broccolini/swiss
twitter_username: tommyprezioso
github_username: Tprezioso
