# Site settings
title: Swift Tom
author:
  name: Thomas Prezioso
  email: tommyprezioso@gmail.com
description: "Learning the Swift Programming Language"
social-network-links:
  twitter: tommyprezioso
  github: Tprezioso
share-links-active:
  twitter: true
  github: true

# Build settings
remote_theme: jekyll/minima
