# Site settings
title: Swift Tom
author: Thomas Prezioso
email: tommyprezioso@gmail.com
description: "Learning the Swift Programming Language"

# Build settings
remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
twitter_username: tommyprezioso
github_username: Tprezioso
