# Site settings
title: Swift Tom
author: Thomas Prezioso
email: tommyprezioso@gmail.com
description: "Learning the Swift Programming Language"

# Build settings
remote_theme: jekyll-sleek
twitter_username: tommyprezioso
github_username: Tprezioso
